### ISSUE TITLE
Msgen Issue

### ISSUE THREAD

**Issue by rs-creator** [microsoft/msgen#5]
Hi,

I have an issue regarding testing the msgen client. Specifically, I downloaded Python 2.7.13 and installed the msgen client.

However, when I downloaded the config files from Azure and tested the client (using msgen list -f “my path file”), it says that it was unable to connect to pypi.python.org to check for updates; afterwards, it says it aborts the task and continues to retry.

Here is a screenshot, for your reference:

<img width="955" alt="ScreenshotTestMsgen" src="https://user-images.githubusercontent.com/80965952/177575788-dcaac687-5a96-4a42-bd15-074c603d4f72.png">

I know that pypi.python.org is no longer used, it is now pypi.org; however, I am unsure how to reconfigure the link or if there is something that I need to update. 

Thanks for your help,

Sincerely,

Roshni

**Comment by rs-creator** [comment]
Hi,

This was the output:

<img width="1481" alt="SSLVersionScreenshot" src="https://user-images.githubusercontent.com/80965952/178031887-c530aff3-bb9d-484a-a447-d9a6a4d5d59e.png">

**Comment by chrishayescodes** [comment]
it appears you have an older version of OpenSSL, this is common on Macs. see: https://github.com/psf/requests/issues/3189

if you don't already have brew installed then I recommend installing it here: https://brew.sh/

once you've done that, follow the instructions here:
https://stackoverflow.com/a/27230127

**Comment by rs-creator** [comment]
Just to make sure, we should first install brew, and then use this following code?:

> pkg install openssl

> OPENSSL_ROOT=/usr/local

> brew install openssl 

> OPENSSL_ROOT="$(brew --prefix openssl)"


Thanks for your help.

**Comment by chrishayescodes** [comment]
quoted from so answer:

> Please refer to http://rkulla.blogspot.kr/2014/03/the-path-to-homebrew.html
> 
> After upgrading openssl to 1.0.1j by homebrew on MAC, but system python still referred to old version 0.9.8. It turned out the python referred to openssl. So I have installed new python with brewed openssl and finished this issue on Mac, not yet Ubuntu.
> 
> On Mac OS X version 10.10 and system python version 2.7.6, my procedure is as follows:
> 
> `$ brew update`
> 
> `$ brew install openssl`
> Then you can see openssl version 1.0.1j.
> 
> `$ brew link openssl --force` 
> 
> `$ brew install python --with-brewed-openssl`    
> You have to install new python with brewed openssl. Then, you can see /usr/local/Cellar/python/2.7.8_2/bin/python.
> 
> `$ sudo ln -s /usr/local/Cellar/python/2.7.8_2/bin/python /usr/local/bin/python`
> 
> Of course, /usr/local/* should be owned by $USER, not root, which is told by Ryan, but I used 'sudo'. And, before this instruction, I didn't have /usr/local/bin/python. After this instruction, you can use python version 2.7.8 not 2.7.6.
> 
> Finally, you can see as belows;
> 
> `$ python --version`  
> Python 2.7.8
> 
> `$ python -c "import ssl; print ssl.OPENSSL_VERSION"`
> OpenSSL 1.0.1j 15 Oct 2014
> Till now, I'm working on it on Ubuntu 12.04. If I have a solution for Ubuntu 12.04, then I will update my answer. I hope this procedure help you.

**Comment by chrishayescodes** [comment]
or you can follow the instructions in the second answer:
> Mac (brew)
> 
> ```
> brew install openssl # DO NOT DO ANY WEIRD SYMLINK HACKS, ITS KEG-ONLY FOR A REASON!
> OPENSSL_ROOT="$(brew --prefix openssl)"
> ```

**Comment by chrishayescodes** [comment]
I would be careful on this line:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/75023401/178040223-9cbec2d4-1f74-488e-8c6f-ee5c04fc2aca.png">
because brew will install a certain version of python
try:
`$ ls /usr/local/Cellar/python`
to identify what version of python brew installed, then alter the link command `ln` shown above to match

**Comment by rs-creator** [comment]
I just have a quick question. Would

`$ brew install python --with-brewed-openssl `

cause brew to install the latest python package(python 3/higher) corresponding to the ssl? The client requires that we use python 2.7.12+.

Thank you very much for your help and your time.

**Comment by chrishayescodes** [comment]
> 

`brew install python` installs python 2.x

the command:
`sudo ln -s /usr/local/Cellar/python/2.7.8_2/bin/python /usr/local/bin/python`
basically overwrites your built-in mac version of python 2.x

**Comment by rs-creator** [comment]
The post is from 2014, so perhaps the syntax is outdated?

As per [https://github.com/Homebrew/brew/issues/891](url), could this work?

`brew link --force /usr/local/opt/openssl/bin/openssl`

Thanks.

**Comment by chrishayescodes** [comment]
I apologize but I don't have a mac to test these changes.

you may attempt to make changes to your system to resolve this issue but my thoughts right now are that you may be best served by setting up a virtual python environment via venv, vms, containers. this way you won't harm your built in version of python on your system.

the main issue with the brew installation is that it doesn't by default overwrite your installed version of python2

see: https://stackoverflow.com/questions/5157678/how-do-i-use-brew-installed-python-as-the-default-python

**Comment by rs-creator** [comment]
Okay, I see. 

Could it be possible to just update the ssl, but then link the installed version of python2? 

Or, uninstall the python2 that was downloaded, and then use the brew-installed python (so we don't have to overwrite the installed version)?

**Comment by chrishayescodes** [comment]
unable to repo. probable client issue with network
